# Configuration/Services.yaml
services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Cabag\CabagLoginas\:
    resource: '../Classes/*'

  Cabag\CabagLoginas\Listeners\RecordList\AddLoginAsUserTableActionListener:
    tags:
      - name: event.listener
        identifier: 'CabagAddLoginAsUserRecordsListTableActionsListener'
        method: 'modifyRecordsListTableActions'
        event: 'TYPO3\CMS\Backend\RecordList\Event\ModifyRecordListTableActionsEvent'
      - name: event.listener
        identifier: 'CabagAddLoginAsUserRecordListRecordActionsListener'
        method: 'modifyRecordListRecordActions'
        event: 'TYPO3\CMS\Backend\RecordList\Event\ModifyRecordListRecordActionsEvent'