# Configuration/Services.yaml
services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

Cabag\CabagLoginas\Listeners\RecordList\AddLoginAsUserTableActionListener:
    tags:
      - name: event.listener
        identifier: 'Cabag/CabagLoginas/Listeners/RecordList/AddLoginAsUserTableActionListener'
        method: 'modifyRecordActions'
